import 'dotenv/config';
import { createServer } from 'node:http';
import { WebSocketServer } from 'ws';
// @ts-expect-error -- generated by `vite build` (adapter-node), only exists after building
import { handler } from './build/handler.js';
import signalingHandler from './src/lib/server/signaling.ts';

const ROUTE = '/signaling';
const port = Number(process.env.PORT ?? 3000);

const server = createServer(handler);
const wss = new WebSocketServer({ noServer: true });

server.on('upgrade', (req, socket, head) => {
	if (!req.url) return;
	const { pathname } = new URL(req.url, 'http://localhost');
	if (pathname !== ROUTE) return;

	wss.handleUpgrade(req, socket, head, (ws) => {
		signalingHandler(ws, req);
	});
});

server.listen(port, () => {
	console.log(`webxr-platform listening on port ${port}`);
});
