// Writes src/lib/xr/ui/icons.generated.ts: the Iconify (Lucide) icons the in-game panels use, and only those, so the
// whole icon set does not end up in the bundle. Add a name below and run `npm run icons`.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const NAMES = ['house', 'users', 'globe', 'backpack', 'settings', 'user', 'folder', 'box'];

const require = createRequire(import.meta.url);
const set = JSON.parse(readFileSync(require.resolve('@iconify-json/lucide/icons.json'), 'utf8'));
const icons = {};
for (const name of NAMES) {
	const icon = set.icons[name] ?? set.icons[set.aliases?.[name]?.parent];
	if (!icon) throw new Error(`No Lucide icon called "${name}"`);
	icons[name] = icon.body;
}
const out = `// Generated by scripts/gen-icons.mjs from @iconify-json/lucide (ISC license). Do not edit by hand.
export const ICON_SIZE = ${set.width ?? 24};

export const ICON_BODIES: Record<string, string> = ${JSON.stringify(icons, null, '\t')};
`;
writeFileSync(new URL('../src/lib/xr/ui/icons.generated.ts', import.meta.url), out);
console.log(`Wrote ${NAMES.length} icons`);
