<script lang="ts">
	import { resolve } from '$app/paths';
	import Scene3D from './Scene3D.svelte';
	let { p = 0 }: { p?: number } = $props();
	const clamp=(v:number)=>Math.max(0,Math.min(1,v));
	const map=(v:number,a:number,b:number)=>clamp((v-a)/(b-a));
	let finale=$derived(map(p,.62,.86));
</script>
<section id="entrar" class="relative"><div id="closing-scroll" class="relative h-[400vh]"><div class="grain sticky top-0 flex h-[100svh] items-center justify-center overflow-hidden"><Scene3D variant="closing" progress={p}/><div class="pointer-events-none absolute inset-0" style="background:radial-gradient(55% 55% at 50% 50%,rgba(7,7,12,.25) 0%,rgba(7,7,12,.82) 100%)"></div><div class="pointer-events-none absolute bottom-10 left-1/2 z-10 -translate-x-1/2 text-center transition-opacity duration-300" style={`opacity:${clamp(1-p*4)}`}><p class="font-display text-[11px] tracking-[.28em] text-bone/45 uppercase">Haz scroll · mira qué queda si quitas todo lo que te rodea</p></div><div class="relative z-10 flex flex-col items-center px-6 text-center transition-opacity duration-300" style={`opacity:${finale};transform:translateY(${(1-finale)*20}px);pointer-events:${finale>.4?'auto':'none'}`}><p class="font-display text-[clamp(1.5rem,5vw,3.4rem)] leading-tight tracking-[-.04em] text-balance">Estás hecho de lo que te rodea.</p><h2 class="mt-10 font-display text-[clamp(2.8rem,10vw,7.5rem)] leading-none font-medium tracking-[-.05em]">KITHIN</h2><div class="mt-9 flex flex-col items-center gap-3 sm:flex-row"><a class="inline-flex items-center gap-3 rounded-full bg-bone px-5 py-3 font-display text-sm font-medium text-ink" href={resolve('/play')}>Entrar <span>→</span></a><a class="rounded-full border border-white/20 px-5 py-3 font-display text-sm" href="#crear">Crear algo</a></div><p class="mt-6 text-[13px] text-bone/45">No necesitas cuenta.</p><p class="mt-10 font-display text-[clamp(1rem,2.4vw,1.5rem)] tracking-tight text-glow/85">Who’s in?</p></div></div></div></section>
